# Generated by Django 4.2.27 on 2026-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cart_product_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='upi_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
